/** Canonical MCP / assistant tool list for Cashish agents (static for client bundles). */
export const TOOL_NAMES = [
  "cashish_dashboard",
  "cashish_upcoming_events",
  "cashish_list_tools_help",
  "cashish_list_accounts",
  "cashish_get_account",
  "cashish_create_account",
  "cashish_rename_account",
  "cashish_archive_account",
  "cashish_update_credit_card_profile",
  "cashish_list_transactions",
  "cashish_search_transactions",
  "cashish_get_transaction",
  "cashish_create_transaction",
  "cashish_list_transfers",
  "cashish_create_transfer",
  "cashish_pay_credit_card",
  "cashish_list_statement_periods",
  "cashish_get_open_statement",
  "cashish_close_statement",
  "cashish_mark_statement_paid",
  "cashish_list_subscriptions",
  "cashish_get_subscription",
  "cashish_create_subscription",
  "cashish_update_subscription",
  "cashish_toggle_subscription",
  "cashish_list_reminders",
  "cashish_dismiss_reminder",
] as const;

export type ToolName = (typeof TOOL_NAMES)[number];
